// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TelematicService.Infrastructure.Contexts;

#nullable disable

namespace TelematicService.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260225174937_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TelematicService.Domain.Entities.CrashDetection", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("Axis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ImpactMagnitude")
                        .HasColumnType("real");

                    b.Property<byte[]>("TelematicsId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.HasKey("Id");

                    b.HasIndex("TelematicsId");

                    b.ToTable("CrashDetections");
                });

            modelBuilder.Entity("TelematicService.Domain.Entities.Telematics", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<int>("Altitude")
                        .HasColumnType("int");

                    b.Property<int>("Angle")
                        .HasColumnType("int");

                    b.Property<float>("BatteryCurrent")
                        .HasColumnType("real");

                    b.Property<int>("BatteryLevel")
                        .HasColumnType("int");

                    b.Property<float>("BatteryVoltage")
                        .HasColumnType("real");

                    b.Property<int>("CanEngineRpm")
                        .HasColumnType("int");

                    b.Property<int>("CanFuelLevelLitres")
                        .HasColumnType("int");

                    b.Property<int>("CanFuelPercentage")
                        .HasColumnType("int");

                    b.Property<int>("CanSpeed")
                        .HasColumnType("int");

                    b.Property<int>("CanTotalMileageMetres")
                        .HasColumnType("int");

                    b.Property<int>("DataMode")
                        .HasColumnType("int");

                    b.Property<bool>("DigitalOutput1")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalOutput2")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalOutput3")
                        .HasColumnType("bit");

                    b.Property<int>("EcoDurationInMS")
                        .HasColumnType("int");

                    b.Property<int>("EcoScore")
                        .HasColumnType("int");

                    b.Property<int>("EngineTemperature")
                        .HasColumnType("int");

                    b.Property<int>("GpsSpeed")
                        .HasColumnType("int");

                    b.Property<int>("GreenDrivingType")
                        .HasColumnType("int");

                    b.Property<int>("GsmSignal")
                        .HasColumnType("int");

                    b.Property<bool>("IdlingAlert")
                        .HasColumnType("bit");

                    b.Property<bool>("IgnitionActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMoving")
                        .HasColumnType("bit");

                    b.Property<float>("Latitude")
                        .HasColumnType("real");

                    b.Property<float>("Longitude")
                        .HasColumnType("real");

                    b.Property<int>("NetworkType")
                        .HasColumnType("int");

                    b.Property<int>("OBDOEMTotalMileageKM")
                        .HasColumnType("int");

                    b.Property<int>("ObdEngineRpm")
                        .HasColumnType("int");

                    b.Property<int>("ObdFuelLevelPercent")
                        .HasColumnType("int");

                    b.Property<int>("ObdOemFuelLevelLitres")
                        .HasColumnType("int");

                    b.Property<bool>("OilIndicatorActive")
                        .HasColumnType("bit");

                    b.Property<bool>("OverSpeedingAlert")
                        .HasColumnType("bit");

                    b.Property<int>("Satellites")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalOdemeterMetres")
                        .HasColumnType("int");

                    b.Property<bool>("TowingAlert")
                        .HasColumnType("bit");

                    b.Property<string>("TripId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TripOdemeter")
                        .HasColumnType("int");

                    b.Property<bool>("UnplugAlert")
                        .HasColumnType("bit");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TimeStamp");

                    b.ToTable("Telematics");
                });

            modelBuilder.Entity("TelematicService.Domain.Entities.CrashDetection", b =>
                {
                    b.HasOne("TelematicService.Domain.Entities.Telematics", "Telematics")
                        .WithMany("CrashDetections")
                        .HasForeignKey("TelematicsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Telematics");
                });

            modelBuilder.Entity("TelematicService.Domain.Entities.Telematics", b =>
                {
                    b.Navigation("CrashDetections");
                });
#pragma warning restore 612, 618
        }
    }
}
